from turtle import *
input=textinput('图形',"您想要什么样的图形？")
speed(10)
# print(input)
if input=='三角形':
    pencolor('red')
    pensize(4)
    fillcolor('blue')
    begin_fill()
    forward(100)
    left(120)
    forward(100)
    left(120)
    forward(100)
    end_fill()
    ht()
    done()
    print(input)
elif input=='矩形':
    pencolor('red')
    pensize(4)
    fillcolor('blue')
    begin_fill()
    forward(200)
    right(90)
    forward(100)
    right(90)
    forward(200)
    right(90)
    forward(100)
    end_fill()
    ht()
    done()
    print(input)
elif input=='正方形':
    print(input)
    pencolor('red')
    pensize(4)
    fillcolor('blue')
    begin_fill()
    forward(100)
    right(90)
    forward(100)
    right(90)
    forward(100)
    right(90)
    forward(100)
    end_fill()
    ht()
    done()
    print(input)
elif input=='圆形':
    pencolor('red')
    pensize(4)
    fillcolor('blue')
    begin_fill()
    circle(100)
    end_fill()
    ht()
    done()
    print(input)
else:
    shape('')
    print(input)

